version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: savetrack-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_123
      MYSQL_DATABASE: finance_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - savetrack-net

  app:
    build: .
    container_name: savetrack-app
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/finance_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root_123
    networks:
      - savetrack-net

volumes:
  mysql_data:

networks:
  savetrack-net:






#version: '3.8'
#
#services:
#  mysql:
#    image: mysql:8.0
#    container_name: savetrack-mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: root_123
#      MYSQL_DATABASE: finance_db
#    ports:
#      - "3307:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#    networks:
#      - savetrack-net
#
#  app:
#    build: .
#    container_name: savetrack-app
#    ports:
#      - "8082:8082"  # Use port 8082 as per your app settings
#    depends_on:
#      - mysql
#    environment:
#      SERVER_PORT: 8082
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/finance_db
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root_123
#    networks:
#      - savetrack-net
#    entrypoint: ["/wait-for-it.sh", "mysql:3306", "--", "java", "-jar", "app.jar"]
#
#volumes:
#  mysql_data:
#
#networks:
#  savetrack-net:
